# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aee69cc28251dadcfff823877f8467e9e57585fa3852d0723cedbb9067d68f072b4f5550c837f35c10eaceef5401619b72c8ccb3c4c917c4f47a0e110350768

test:
  secret_key_base: 8a1aa77c19e3121426ec188374df84d3c118bf181b4f67585e4fc455147ca0c57e8e7d69d679900207eb4ca23eef66018d8d311f6cce1e01ae9288eada42b4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
